services:
  db:
    image: postgres:latest
    container_name: bot_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data

  bot:
    container_name: bot
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/bot
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"